CREATE DATABASE db_seriesandmovies;
GO

USE db_seriesandmovies;
GO

CREATE TABLE [GenreTypes] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL
);

CREATE TABLE [Countries] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(40) NOT NULL,
	[Code] VARCHAR(10) NOT NULL
);

CREATE TABLE [Languages] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(40) NOT NULL,
	[Code] VARCHAR(10) NOT NULL
);

CREATE TABLE [ContentTypes] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(200) NULL
);

CREATE TABLE [RoleTypes] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL
);

CREATE TABLE [Plans] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(200) NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[MaxPeople] INT NOT NULL
);

CREATE TABLE [UserAccounts] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Lastname] VARCHAR(100) NOT NULL,
	[Username] VARCHAR(50) NOT NULL,
	[PhoneNumber] VARCHAR(15) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(30) NOT NULL,
	[Birthday] DATETIME NOT NULL
);

CREATE TABLE [Studios] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[Country] INT FOREIGN KEY REFERENCES [Countries]([Id]),
	[Description] VARCHAR(200) NULL
);

CREATE TABLE [Persons] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[Lastame] VARCHAR(100) NOT NULL,
	[Birthday] DATETIME NULL,
	[Description] VARCHAR(100) NULL
);

CREATE TABLE [Contents] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(100) NULL,
	[ContentType] INT FOREIGN KEY REFERENCES [ContentTypes]([Id]),
	[Year] DATETIME NULL,
	[Language] INT FOREIGN KEY REFERENCES [Languages]([Id]),
	[Studio] INT FOREIGN KEY REFERENCES [Studios]([Id]),
	[Person] INT FOREIGN KEY REFERENCES [Persons]([Id])
);

CREATE TABLE [ContentGenres] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[GenreType] INT FOREIGN KEY REFERENCES [GenreTypes]([Id]),
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id])
);

CREATE TABLE [Seasons] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[NumberSeason] INT NOT NULL,
	[Title] VARCHAR(100) NOT NULL,
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id]),
	[Description] VARCHAR(200) NULL,
	[ReleasedAt] DATETIME NULL
);

CREATE TABLE [Episodes] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Season] INT FOREIGN KEY REFERENCES [Seasons]([Id]),
	[Title] VARCHAR(100) NOT NULL,
	[NumberEpisode] VARCHAR(100) NOT NULL,
	[DurationTime] TIME(2) NOT NULL,
	[Description] VARCHAR(200) NULL,
	[ReleasedAt] DATETIME NULL
);

CREATE TABLE [Reviews] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[User] INT FOREIGN KEY REFERENCES [UserAccounts]([Id]),
	[Comment] VARCHAR(150) NULL,
	[Rating] INT NULL,
	[CreatedAt] DATETIME NOT NULL,
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id])
);

CREATE TABLE [Subscriptions] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[User] INT FOREIGN KEY REFERENCES [UserAccounts]([Id]),
	[Plan] INT FOREIGN KEY REFERENCES [Plans]([Id]),
	[StartedAt] DATETIME NOT NULL,
	[FinishedAt] DATETIME NOT NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[Months] INT NOT NULL,
	[Status] BIT NOT NULL
);

CREATE TABLE [AudioTracks] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id]),
	[Language] INT FOREIGN KEY REFERENCES [Languages]([Id])
);

CREATE TABLE [Subtitles] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id]),
	[Language] INT FOREIGN KEY REFERENCES [Languages]([Id])
);

CREATE TABLE [Watchlists] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[User] INT FOREIGN KEY REFERENCES [UserAccounts]([Id]),
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id])
);

CREATE TABLE [PersonTypeRoles] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Person] INT FOREIGN KEY REFERENCES [Persons]([Id]),
	[RoleType] INT FOREIGN KEY REFERENCES [RoleTypes]([Id])
);

CREATE TABLE [Credits] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Person] INT FOREIGN KEY REFERENCES [Persons]([Id]),
	[Content] INT FOREIGN KEY REFERENCES [Contents]([Id]),
	[RoleType] INT NOT NULL FOREIGN KEY REFERENCES [RoleTypes]([Id])
);

GO